# Generated by Django 3.0.6 on 2020-06-02 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FIRSTAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name_plural': 'ContactInfo'},
        ),
        migrations.RenameField(
            model_name='contactinfo',
            old_name='email_address',
            new_name='email',
        ),
    ]
