# Generated by Django 3.0.6 on 2020-05-25 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='property_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=10)),
                ('zip', models.CharField(max_length=10)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myfirstapp.property_type')),
            ],
        ),
    ]
