# Generated by Django 3.0.6 on 2020-05-29 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0004_auto_20200526_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('vpassword', models.CharField(max_length=50)),
                ('prop_type', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Register',
            },
        ),
    ]
