# Generated by Django 3.0.6 on 2020-05-31 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0005_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
